#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if  git rev-parse -q --no-revs --verify MERGE_HEAD
then
echo -e "\n${red}MERGE REJECTED! Please fix conficts before committing.\n${no_color}"
else
    npx lint-staged
fi





red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
no_color='\033[0m'

echo -e "\n${yellow}Executing pre-commit hook...${no_color}\n"

FILES_PATTERN='\.(js|ts)(\..+)?$'
FORBIDDEN='console\.[clear|dir|log|info]'

#check for console. references in your code

if git diff -U0 --cached --name-only | \
    grep -E $FILES_PATTERN | \
    xargs grep --with-filename -n $FORBIDDEN | \
    grep -v '//';
then
    echo -e "\n${red}COMMIT REJECTED!  Found console. references. Please remove them before committing.\n${no_color}"
    exit 1;
fi
echo -e "${green}No console. references found!${no_color}\n"
echo -e "${green}Git pre-commit hook was successful!${no_color}\n"
exit 0;

